services:
  jellyfin:
    container_name: jellyfin
    networks:
      - default
      - traefik_proxy
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    devices:
      - /dev/dri:/dev/dri
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Jellyfin:/config
      - /mnt/BigPool/Media:/media
    tmpfs:
      - /transcode:mode=0777
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.noms.tv`)
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096
      - traefik.http.services.jellyfin.loadbalancer.server.scheme=http
      - traefik.http.routers.jellyfin.service=jellyfin
      - traefik.http.routers.jellyfin.tls=true
networks:
  default:
    name: media_services
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true