services:
  plex:
    container_name: plex
    network_mode: host
    environment:
      - TZ=America/New_York
      - ALLOWED_NETWORKS=10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      - PLEX_CLAIM=''
      - PLEX_GID=568
      - PLEX_UID=568
    devices:
      - /dev/dri:/dev/dri
    image: plexinc/pms-docker:plexpass
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Plex/config:/config
      - /mnt/BigPool/Media:/data
    tmpfs:
      - /config/Library/Application Support/Plex Media Server/Logs
      - /transcode:mode=0777
    healthcheck:
      interval: 10s
      retries: 30
      start_period: 10s
      test: /healthcheck.sh
      timeout: 5s