services:
  readarr:
    container_name: readarr
    networks:
      - default
      - traefik_proxy
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
    image: lscr.io/linuxserver/readarr:develop
    # ports:
    #   - '8787:8787'
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Readarr:/config
      - /mnt/Scratch/Downloads:/ScratchDownloads
      - /mnt/BigPool/Downloads:/BigPoolDownloads
      - /mnt/BigPool/Media:/PlexMedia
    labels:
      - traefik.enable=true
      - traefik.http.routers.readarr.entrypoints=websecure
      - traefik.http.routers.readarr.rule=Host(`readarr.noms.tv`)
      - traefik.http.services.readarr.loadbalancer.server.port=8787
      - traefik.http.services.readarr.loadbalancer.server.scheme=http
      - traefik.http.routers.readarr.service=readarr
      - traefik.http.routers.readarr.tls=true
      ###
      # Authentik Enablement
      - traefik.http.routers.readarr.middlewares=authentik@file
      - traefik.http.routers.readarr.priority=10
      - traefik.http.routers.readarr-auth.rule=Host(`readarr.noms.tv`) && PathPrefix(`/outpost.goauthentik.io/`)
      - traefik.http.routers.readarr-auth.priority=15
      ###
networks:
  default:
    name: media_services
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true