services:
  tdarr:
    container_name: tdarr
    image: ghcr.io/haveagitgat/tdarr:latest
    restart: unless-stopped
    networks:
      - default
      - traefik_proxy
    ports:
      - 8265:8265 # webUI port
      - 8266:8266 # server port
    environment:
      - TZ=America/New_York
      - PUID=568
      - PGID=568
      - UMASK_SET=002
      - serverIP=0.0.0.0
      - serverPort=8266
      - webUIPort=8265
      - internalNode=fals
      - inContainer=true
      - ffmpegVersion=7
    volumes:
      - /mnt/AppData/Tdarr/server:/app/server
      - /mnt/AppData/Tdarr/configs:/app/configs
      - /mnt/AppData/Tdarr/logs:/app/logs
      - /mnt/BigPool/Media:/media
      - /mnt/Scratch/Tdarr:/temp
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    labels:
      - traefik.enable=true
      - traefik.http.routers.tdarr.entrypoints=websecure
      - traefik.http.routers.tdarr.rule=Host(`tdarr.noms.tv`)
      - traefik.http.services.tdarr.loadbalancer.server.port=8265
      - traefik.http.services.tdarr.loadbalancer.server.scheme=http
      - traefik.http.routers.tdarr.service=tdarr
      - traefik.http.routers.tdarr.tls=true
  tdarr-node:
    container_name: tdarr-node
    image: ghcr.io/haveagitgat/tdarr_node:latest
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - PUID=568
      - PGID=568
      - UMASK_SET=002
      - nodeName=TrueNas
      - serverIP=172.16.1.10
      - serverPort=8266
      - inContainer=true
      - ffmpegVersion=7
    volumes:
      - /mnt/AppData/Tdarr/configs:/app/configs
      - /mnt/AppData/Tdarr/logs:/app/logs
      - /mnt/BigPool/Media:/media
      - /mnt/Scratch/Tdarr/Node-TrueNas:/temp
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
networks:
  default:
    name: media_services
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true