services:
  overseerr:
    container_name: overseerr
    networks:
      - default
      - traefik_proxy
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
    image: lscr.io/linuxserver/overseerr:latest
    # ports:
    #   - '5055:5055'
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Overseerr:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.overseerr.entrypoints=websecure
      - traefik.http.routers.overseerr.rule=Host(`request.noms.tv`)
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      - traefik.http.services.overseerr.loadbalancer.server.scheme=http
      - traefik.http.routers.overseerr.service=overseerr
      - traefik.http.routers.overseerr.tls=true
networks:
  default:
    name: media_services
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true