services:
  sabnzbd:
    container_name: sabnzbd
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
    image: lscr.io/linuxserver/sabnzbd:latest
    networks:
      - default
      - traefik_proxy
    ports:
      - '8080:8080'
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Sabnzbd/config:/config
      - /mnt/Scratch/Downloads:/ScratchDownloads
      - /mnt/BigPool/Downloads:/BigPoolDownloads
    labels:
      - traefik.enable=true
      - traefik.http.routers.sabnzbd.entrypoints=websecure
      - traefik.http.routers.sabnzbd.rule=Host(`sabnzbd.noms.tv`)
      - traefik.http.services.sabnzbd.loadbalancer.server.port=8080
      - traefik.http.services.sabnzbd.loadbalancer.server.scheme=http
      - traefik.http.routers.sabnzbd.service=sabnzbd
      - traefik.http.routers.sabnzbd.tls=true
networks:
  default:
    name: media_services
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true