services:
  huntarr:
    container_name: huntarr
    networks:
      - default
      - traefik_proxy
    environment:
      - TZ=America/New_York
    image: huntarr/huntarr:latest
    # ports:
    #   - '9705:9705'
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Huntarr:/config
    labels:
      - traefik.enable=true
      - traefik.http.routers.huntarr.entrypoints=websecure
      - traefik.http.routers.huntarr.rule=Host(`huntarr.noms.tv`)
      - traefik.http.services.huntarr.loadbalancer.server.port=9705
      - traefik.http.services.huntarr.loadbalancer.server.scheme=http
      - traefik.http.routers.huntarr.service=huntarr
      - traefik.http.routers.huntarr.tls=true
networks:
  default:
    name: media_services
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true