services:
  radarr:
    container_name: radarr
    networks:
      - default
      - database_network
      - traefik_proxy
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/New_York
    image: lscr.io/linuxserver/radarr:latest
    # ports:
    #   - '7878:7878'
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Radarr:/config
      - /mnt/Scratch/Downloads:/ScratchDownloads
      - /mnt/BigPool/Downloads:/BigPoolDownloads
      - /mnt/BigPool/Media:/PlexMedia
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.rule=Host(`radarr.noms.tv`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.services.radarr.loadbalancer.server.scheme=http
      - traefik.http.routers.radarr.service=radarr
      - traefik.http.routers.radarr.tls=true
      ###
      # Authentik Enablement
      - traefik.http.routers.radarr.middlewares=authentik@file
      - traefik.http.routers.radarr.priority=10
      - traefik.http.routers.radarr-auth.rule=Host(`radarr.noms.tv`) && PathPrefix(`/outpost.goauthentik.io/`)
      - traefik.http.routers.radarr-auth.priority=15
      ###
networks:
  default:
    name: media_services
    external: true
  database_network:
    name: database_network
    external: true
  traefik_proxy:
    name: traefik_proxy
    external: true