services:
  authentik-proxy:
    container_name: authentik-proxy
    networks:
      - traefik_proxy
    env_file: .env
    image: ghcr.io/goauthentik/proxy:2024.10.5
    ports:
      - '9000:9000'
      - '9443:9443'
    restart: unless-stopped
networks:
  traefik_proxy:
    name: traefik_proxy
    external: true