services:
  mediadb:
    image: postgres:17.5
    container_name: mediadb
    env_file: ./.env
    networks:
      - deafult
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Postgres/mediadb:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file: ./.env
    networks:
      - deafult
      - traefik_proxy
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Postgres/pgadmin:/var/lib/pgadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.entrypoints=websecure
      - traefik.http.routers.pgadmin.rule=Host(`truenas-pgadmin.int.noms.tv`)
      - traefik.http.services.pgadmin.loadbalancer.server.port=80
      - traefik.http.services.pgadmin.loadbalancer.server.scheme=http
      - traefik.http.routers.pgadmin.service=pgadmin
      - traefik.http.routers.pgadmin.tls=true
networks:
  deafult:
   name: database_network
   driver: bridge
   ipam:
     config:
       - subnet: 10.0.2.0/24
         gateway: 10.0.2.1
  traefik_proxy:
    name: traefik_proxy
    external: true