[[stack]]
name = "channels-dvr"
tags = ["truenas"]
[stack.config]
server = "truenas"
poll_for_updates = true
git_account = "Nomsplease"
repo = "Nomsplease/Komodo_Stacks"
run_directory = "truenas/channels-dvr"

##