## Channels DVR
[[stack]]
name = "channels-dvr"
tags = ["truenas"]
[stack.config]
server = "truenas"
poll_for_updates = true
auto_update = true
git_account = "nomsplease"
repo = "Nomsplease/Komodo_Stacks"
run_directory = "truenas/channels-dvr"

## Plex
[[stack]]
name = "plex"
tags = ["truenas"]
[stack.config]
server = "truenas"
poll_for_updates = true
auto_update = true
git_account = "nomsplease"
repo = "Nomsplease/Komodo_Stacks"
run_directory = "truenas/plex"