services:
  garage:
    container_name: garage
    networks:
      - traefik_proxy
    image: dxflrs/garage:v1.1.0
    # ports:
    #   - '3900:3900' #S3 Port
    #   - '3902:3902' #S3 Web Port
    labels:
      - traefik.enable=true
      - traefik.http.routers.garage-s3.entrypoints=websecure
      - "traefik.http.routers.garage-s3.rule=Host(`s3-new.noms.tv`) || HostRegexp(`{subdomain:.+}.s3-new.noms.tv`)"
      - traefik.http.services.garage-s3.loadbalancer.server.port=3900
      - traefik.http.services.garage-s3.loadbalancer.server.scheme=http
      - traefik.http.routers.garage-s3.service=garage-s3
      - traefik.http.routers.garage-s3e.tls=true
      - traefik.http.routers.garage-s3-web.entrypoints=websecure
      - traefik.http.routers.garage-s3-web.rule="Host(`s3-web.noms.tv`) || HostRegexp(`^.+\.s3-web\.noms\.tv$`)"
      - traefik.http.services.garage-s3-web.loadbalancer.server.port=3902
      - traefik.http.services.garage-s3-web.loadbalancer.server.scheme=http
      - traefik.http.routers.garage-s3-web.service=garage-s3-web
      - traefik.http.routers.garage-s3-web.tls=true
    restart: unless-stopped
    volumes:
      - /mnt/AppData/Garage/garage.toml:/etc/garage.toml
      - /mnt/AppData/Garage/meta:/var/lib/garage/meta
      - /mnt/BigPool/Garage/data:/var/lib/garage/data
networks:
  traefik_proxy:
    name: traefik_proxy
    external: true